name: 'Create Image'
on:
  pull_request:
    branches:
      - main

jobs:
  Generate:
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'  }}
    permissions:
      issues: write
      pull-requests: write
      discussions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-token: ${{ secrets.OPEN_AI_API_TOKEN }}
